apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.jetstack.io
    name: trust-manager
    version: v0.20.2
    includeCRDs: true
    releaseName: trust-manager
    valuesFile: values.yaml
    namespace: trust-manager
