apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../helm-charts

helmCharts:
  - name: namespace
    releaseName: namespace
    valuesFile: values.yaml
