image:
  repository: "ghcr.io/hotio/sonarr"
  tag: "release-4.0.16.2944@sha256:0e5d98a3fe8315f6a9432479a4c4156beefe52f13c084a2ba842ad847f2ae312"

ports:
  - name: main
    containerPort: 8989

gateway:
  host: sonarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/sonarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: series
    hostPath: /srv/hdd/multimedia/Serien-Sonarr
    containerPath: /series

homepage:
  name: Sonarr
  group: Indexer
  description: Serien Manager
  icon: sonarr.svg
  weight: 13
