image:
  repository: "ghcr.io/dani-garcia/vaultwarden"
  tag: "1.32.0@sha256:71668d20d4208d70919cf8cb3caf3071d41ed4b7d95afe71125ccad8408b040d"

hostPaths:
- name: data
  hostPath: /srv/nvme/container-data/vaultwarden/data
  containerPath: /data

ports: 
- name: main
  containerPort: 80

ingress:
  host: vault.wagner.gg
  public: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

homepage:
  name: Vaultwarden
  group: Cloud
  description: Password Manager
  icon: bitwarden.svg
  weight: 1

database:
  enabled: true
  hostPath: /srv/nvme/container-data/vaultwarden/database
  rootPassword: AgBSqF1wtbop1WWWArHRzyJCajshVlKyqp2FB8SdB78iOGvBWsmYbazQkXVf+m/U5zje9ILmTcEuSUAaPPrDqODjjgdywbIWkFbs07Vwm3KHcm8L0z8ro2s2EB3NoutYIyGAa05bbT6h7CjW79RjPD6SYEECwmG3p5WkFHwb1tAFpFq1U14gyhZDrfmYGGR12XmJmoh9CTc9Co2K0lPHuTD3S/2A4PNaMZVfB2MQkPAPPlOQdEbT3rDtF+bnODcHE563JM22hGkZAVRIwwGOj9TE0CEj/fQilrNVFn1H9ciDtg4xKhDqcd2C+eDhSnbpczvAOzJWvmPX4SjYllqO/sFlTFjOQtvvTdI1eaPoLAPbyMVzi72nhEul0BM82iUJdmz5aF0zc2e7MwTwIV9KQJm0nkS05Tuo8bopjg6kuGWfi+at9B3zdo622cn4aTUcXWEcFtIc3FqA6cG2VOkGapg8poYbvD6PGjtEAVR39kLMXFImMBmtb0XNrzebJl51bOGWEcEb12rf8ESqq3fVbTuPFb5XnbWobKTBEo5w+irBVRpRhloe8Pt0vYxB8AdIAXRx9z0u3gS4N75KmlZfwwpDd027M+FZrCBysE1epwDYz3X+QuOcFP9lQ/6+M7HVTA5LJuv9beFA0LJAWfhGgSXTWmmW2O3BQJXCXv76vcVz+BIATjuwLYBkOyqEDZ4u7yOrpmM03PLEo4DmvPXvNvglkRwXgmM/6dpkYNULJ2R9awhF9g6u50BrxP1vzuvZ062M03saGJeqtWAxUma4+LNO
  userPassword: AgBUmZ4sDkAsX0rL32HAbPTynYIoNb+1Qj1hExBOp5+cK1foMkjpSysYlI262CSbG00kv+6WZ/fMb5UJLTfYuUdlQPaTx+tPZpXKPMEdPnbCStF3ILStUFcDYi4OeKh3m1cFLsJPqmJxfUVQcNJ75t5KRmQncdnr7mYg/G64w51SnZQ4goaDolOruZENVYiqLrEsV7YFNZJ8LgE67Csp2nmAKbcBjcglwrxyzNn3oBn5x7oPJuHxDQyWSjVBVwcUiaKRY2aDaPdGCn3KrmE6sgRwxYo8KfP9JVs1kIGv57DJ3Y89JaCdCRWJCG+qdIJMYOBf0UrDOscU3MFzRCkwNinJs4VxfOFFsktw07eLdeMIPsIRIlvnpCVM9NXoDBUm7vYzH/TnQFpY0IiqCQrKg51943QUv05Li6VG9n4X2ik2AcI/JtoDMgqJwn8igYZOqhwRzPnLxsMzHBFs+oIBWDLYg18/RVwgkLwOJUBa0qDagsxXlOj73R+cyQOK8jUk5Sl+XFS2V7/3NfQ5Bx7bxty3wQ4jKSO4PWnoG6cne0xbdCjSQNDDv7cSwCx7dVFvMVjftQ5yevZyarlnN/SYwwDEYgmWw9SeWJLgpSQFVK9R6ytL+Y1YPwICi9M2QHLfSBCrYFRaqaWFmN32HzjbfXu35w6ydPYxDJmM4s/EvSNrB/n5WGx79eAl3I5pi3K1FU6fcCpO2q7OG8MGsu/mHLE52LQcE9XTWxOmGCEW72GhwESL3fBIK36IaOLjrDijQtyDCrjnkplCJkrGUiDnLhsa

envs:
- SIGNUPS_ALLOWED: false
- INVITATIONS_ALLOWED: false
- DOMAIN: https://vault.wagner.gg
- SHOW_PASSWORD_HINT: false
- PASSWORD_ITERATIONS: "1000000"
- ICON_SERVICE: bitwarden
- DATABASE_URL: mysql://$(TEMPLATE_DB_USERNAME):$(TEMPLATE_DB_PASSWORD)@$(TEMPLATE_DB_HOST):$(TEMPLATE_DB_PORT)/$(TEMPLATE_DB_DATABASE)
- ADMIN_TOKEN: $argon2id$v=19$m=65540,t=3,p=4$U0g2SFVGRWJKWWNsdVloS0lMQXVOV3lKZS9BUXc0V1A0QzJqUE9WcDUzRT0$bxhRneNd4uVDYirTsD9FOHG5tQTQlahp1NhGg9AcqTM
# Email
- REQUIRE_DEVICE_EMAIL: true
- SMTP_HOST: smtp.migadu.com
- SMTP_PORT: 587
- SMTP_SECURITY: starttls
# push
- PUSH_ENABLED: true
- PUSH_RELAY_URI: https://api.bitwarden.eu
- PUSH_IDENTITY_URI: https://identity.bitwarden.eu

secretEnvs:
- SMTP_FROM: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
- SMTP_USERNAME: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
- SMTP_PASSWORD: AgCzzndqBjY2iJ746hwzJXiJ5vMOU43ubyIOICoV1k4VUZq/sdblc5t5jcYPIWwa2VC1NzRp5Xvaqq0PjcTjr/RDAwyVZ+9lwtJBI2E8/M9Zd99MjihcY1zVjB0uKRwIvDiIKieZ6WQfPiE4lPbGX7cHQzJTu8wItYZ246IzbKvZXi2oGANdWK6AOWb1M8lC2DTo7UJ6N+AjQZblk0T/Imw3kpnRTi3Z1pZOl6BbBNBHBx1zzGX2Bgk7uic1CoUNR0Np+rEF8Ji7lmBFczosjSpbf64jSLm6E8Uy+89HhijQgFqCqaxU0DMlNe617pmHQVWqI6BfWGvEJ+mMk0L7p9cRNx8NNlKVUAnu8zkRdZjp5ccbnIhjMEtGznS4+Z3Qcw8mHYaD3aaY30Wy/4RpfofUttHGp7YObS8IIEMBVF9otZkmFFjM2cFrZ4IG2Zzuat+T+hIsRv+YnD2rOOw/Q3PvvtvRdrGi5UrhdMDrfjO+SQfVDd3Bu+JUGzAWBkWR67ZXvpwZDTUzcFgUYrqfsDAYj4FEycvTfbVKRy65GxLdJWZxD1FvticZphWaWy+z3wuhbLjWacu+GHV86fl8q1dy+3JNwlAa2F1nF3wIVq3Q+VwZHC7RB2u+juJt0YsGc+3myFyYojIwq43xojDP3NztuQQOr73EpUUUrejA4DBWfwYuG5XVlb9OvhR7es9aPbJV4manNwWOjfiuPiOGpaAgxQWIZvQskGsW68U0jIpQnW1Fjm95D6BEMztLBQ==
# push
# https://github.com/dani-garcia/vaultwarden/pull/3304
# https://bitwarden.com/host/
- PUSH_INSTALLATION_ID: AgBkgVd8+NG8FNT9IusGgxIecTIhlFH/BUaZR2lzgYWpvijYUXZvdToaOyGZigKGcPPdl2DH9o6GycmWyRl/w9kbP8DdKIG79GEUeo3i3Uf55EvVRCexWOgCsTeYfV6xvdt0FeMfW6bZpib7dxlv1GVMMVdLCaqkzFQa8DtNMqFKdI4B93UYP4h4UR6R8yAjiCsPRUyHyKXBlnVUHhRJB2staQFrlQbLs7jdZxFWKE6xZUpF3SdwBSmhDNJiM1JzzjDMiGnameC9Lx87VPexxLjPn2kEkKrSZsYgk1ItHZgDX4XoInkWVaZGgbHnU+KJwMTb7JL3NbimyhaJrqmN+/1VVHp2wHhwPjgIw3vmL/AHccvVFi12Tnlwsq6gxgeFd3IsY9tFm5t61qS+ZQ4+ezQrapSkSLzpQm50dTAfnj/trlI3pD1GpEQrEPxk5Yq6koH/xVLLJQ8bZEmSq8MKdTD6oVCePBolBRRsrmeCb1H0ZLj/tN/rJiQ7FmC8KH6R28k5w9gmlrSxnKFP+1edam/H/oKNRPjqUDYVdV0q832vF98HqbwLQU2wOyszVA+KUa7cX5OrEieFlsejlABFgtlE5IlcSQU0bdg1NkENqBWPGYLLPnSZkzbZOCAIVE9otJ88lQavO1sKI3MMRTbqcjVaAteCNP/hLTbmQyG4h4FpFG8krXNeXUXJsr8wMgZIbU54vDe24XT/ni8L/t0CI/tO+twZsXlaY0vhOxYUhQPZX0ddFqw=
- PUSH_INSTALLATION_KEY: AgBGSEuRskJsWNAx4ov1h15lQuMXt8MZ6l2T5D3xSw9kRxGqE9GnjHa9nB7LH/GUNjbPuqhXGmGZPvD3FX2hNvVl2iKVaPssSEaSjMQPt+F6mehJb33kI5mO+vUI/aUh/PU9yPdAS5W+6oL1HuKjlwiPuobn/hbpS4dWCyoiyBt1zWpW0vDYV9lSdr398RHtlz81+rmFPN/BKetDDc0RFBjcybrqL7tZ41AmLE2T9VDPJ4jImzqRit0W9yqYnM6hKVsRqezb1m4Ij3HCgFHvXU5/74nk3uKnWNjhKyvUfGEzxcqszsgZ7HUVNPTMzVTnB6utXh4FCziTwZDyt9afXv7HHkMIvLbqJlM81/hDRXojwIm5eMFzGCMXly1UepC+Uqy6c6tDk4q21q6jOUkuXQ5sm7pMcMMCstqlXV4/ZXeJO8J6Ji6di/xQrD0lUgbtfEy3O1s3H7vIA0wB8YRvLq9nlGZljb+F9235F1ywQW0DOgLxN+k3/7WoSyRZ4+qkYV9MWCWZkNBCfoXuZYY02Lk1W/2AvL6JCR8c8ZqJVoax38hLJZy++f8eH//D3n2DGWpqfn9cA2kn83ZT0y1lYcziyJywHRx75I2fBn3cPG+7Z9MVL5l8cv+R5Glh8hn74jBF9iSY4W9epD4yy4Ifq2EgNWeyQpL1SWik2VzQN8nPcgldIxQv+m7l2DMpuVOj3fF9dlVAuxA62K+K1INsEQ+InyqQbQ==
