controller:
  terminationGracePeriodSeconds: 30

  extraArgs:
    default-ssl-certificate: network/wildcard-wagner.gg

  config:
    enable-brotli: "true"
    use-gzip: "true"
    log-format-upstream: 'status=$status proxy_upstream_name=$proxy_upstream_name x_forward_for=$proxy_add_x_forwarded_for vhost=$host request_id=$req_id request_time=$request_time request_method=$request_method request_proto=$server_protocol request_path=$uri request_query=$args request_length=$request_length bytes_sent=$bytes_sent http_referrer=$http_referer http_user_agent="$http_user_agent" upstream_status=$upstream_status upstream_response_time=$upstream_response_time upstream_response_length=$upstream_response_length upstream_addr=$upstream_addr time=$time_iso8601'

  admissionWebhooks:
    enabled: false

  service:
    type: ClusterIP

  ingressClassResource:
    name: nginx-public
    controllerValue: k8s.io/ingress-nginx-public
