image:
  repository: "ghcr.io/pocket-id/pocket-id"
  tag: "v2.3.0-distroless@sha256:85a7485108325e34679b0fbca0baeb8418401f6d6cf59944d50f3ec013aafd09"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/pocket-id
    containerPath: /app/data

health:
  path: /health
  public: true

envs:
  - APP_URL: https://id.wagner.gg
  - TRUST_PROXY: true
  - ANALYTICS_DISABLED: true
  - UI_CONFIG_DISABLED: true
  - SMTP_TLS: starttls
  - SMTP_HOST: smtp.migadu.com
  - SMTP_PORT: 587
  - EMAIL_LOGIN_NOTIFICATION_ENABLED: true
  - EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: true
  - EMAIL_API_KEY_EXPIRATION_ENABLED: true

secretEnvs:
  - MAXMIND_LICENSE_KEY: AgCb7xWnSszDTkDaczDGEJKtGQUULZQUCil0LYuWlNAnKcZJdB5DFOdz/AMGJgexDngpVhSF2gNeqOJcuvebPfF7qiVoEU62TDsjxwL2I0llj3371s4QI9ZWNLYyAAeh2Y73NsW2NgZlv5PBeemfjELSNuEVGyRs5hq4o2YGPAsiX1rq+uzjcsuc5w9l4nf5nwD2Y4P2t2K0q4EsqFgKZVyj0gOmiPYbRWESu13HhnbrfQsUHGhlTLnF6eW7zcrCZW5F48KHYW7BOMs84CTBO0JJXP4gI0r356Jd+29W3y7JUAw54XiuJj9M1iLDKLpFL1u8cO+0gJ7zMo0dtp2aHrA5ugktpET8juiY8H6MrMATep4be4MDwt44ySsQ08rTWhsw7y5Z4KhUrCKs+nL/6WRNoG4hYXlStMsyTsBdQnFtIVVmzTmc38ZxnWK5OMABw5sTe+4hnhRg85JICE2Gdrbi7ZDK3PjWygnE57xwaZ+PCJu6s8U/YQnK6oxI/6wJiwq1oKHxLPq6lH/NZ3PtDlp51+dKdoTJpzSkWGqpp97NywJgw+349RXF1kJ5slf+l+RNddDwiEO3RxheIONCnImHPjgjt9mFhk4G58Y3MVuVbyCyR1YDOub9USPVZIkAUg9hAmiD3rBSdrjPTLfF+YZn43ilQZblmdo/bsQP/rPOq1e2YzaA0xyCVzWtVraPNSHHL9P8fYaUstw4C9KzaSM/ZkN16+3eR/1QtW70EqmBAIaiX7eju143
  - ENCRYPTION_KEY: AgCLo2TBGg1p6JPwpO1XLOwGIHqN5mPg5KsDhSKgkEsfzeXqaIViNM+2Xybnaq8Y45yEYpKBp9HWmfQktaPM1vGqJhstinB2y4GDc0NElhOhPkXcVp9LjyFB9E94HVOXezVb6u4Iq6yxYWPrcTK5iQvHMfKweu+ypw4c/4EFhvS61/XF2TdfLeFPehpmgYYmqQMvXrKSQD5kmyoKNLm3ChDGN1jP2rpNwU7WR8D1tMzMzSD8LVYZ03oMFdnM/5JmIdWQ9wBUDlUdEIvfOlZ9pqfup7X9mSmD2yyQrMny6exg7IBcCuTitQ9RICM2SU9Hge7060K3JA/PPnGEVK/V4S+EYp56wBa5k5l9TlV0LxlrKCa59jEklnycHfGM5U059PN8OgnO9MgL/m/o0xBLrC44WJKVgJMfRGWOCT1J8pM590mLDIYjLK2A12bg44IadKwWqov1Xxm2mFGvr8U4SWk1XtuGYnwmQzT69L3xa3FTaYNQysj9GpQuehYWXZE9Egg5xnAEEqJ86pGHq/88q6p/T+T1JaXiwk6ml2Jbwst4Q75OtzYdMUDzhQjZj8cripiKTdU6RkDtW40eW/vkfxP8NrZQvi4uSd5ZO+wOh/8/Bt9KTXd95AFnZN2qCUDvQ6ZBjq51eO7MrIEM0chRc/Q0QcaE40aZjSY6pH62wMI/3CtBmlv7OGqDRtkTGqxnQtON9E1MS1dprXL/twphMF7e4RQ3H8/5usaP+ItwGF2/pQdlXTGCdlGT+RgR7C8pPVHXbwiJJ24CSPgpBs4NXMGR
  - SMTP_FROM: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
  - SMTP_USER: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
  - SMTP_PASSWORD: AgCzzndqBjY2iJ746hwzJXiJ5vMOU43ubyIOICoV1k4VUZq/sdblc5t5jcYPIWwa2VC1NzRp5Xvaqq0PjcTjr/RDAwyVZ+9lwtJBI2E8/M9Zd99MjihcY1zVjB0uKRwIvDiIKieZ6WQfPiE4lPbGX7cHQzJTu8wItYZ246IzbKvZXi2oGANdWK6AOWb1M8lC2DTo7UJ6N+AjQZblk0T/Imw3kpnRTi3Z1pZOl6BbBNBHBx1zzGX2Bgk7uic1CoUNR0Np+rEF8Ji7lmBFczosjSpbf64jSLm6E8Uy+89HhijQgFqCqaxU0DMlNe617pmHQVWqI6BfWGvEJ+mMk0L7p9cRNx8NNlKVUAnu8zkRdZjp5ccbnIhjMEtGznS4+Z3Qcw8mHYaD3aaY30Wy/4RpfofUttHGp7YObS8IIEMBVF9otZkmFFjM2cFrZ4IG2Zzuat+T+hIsRv+YnD2rOOw/Q3PvvtvRdrGi5UrhdMDrfjO+SQfVDd3Bu+JUGzAWBkWR67ZXvpwZDTUzcFgUYrqfsDAYj4FEycvTfbVKRy65GxLdJWZxD1FvticZphWaWy+z3wuhbLjWacu+GHV86fl8q1dy+3JNwlAa2F1nF3wIVq3Q+VwZHC7RB2u+juJt0YsGc+3myFyYojIwq43xojDP3NztuQQOr73EpUUUrejA4DBWfwYuG5XVlb9OvhR7es9aPbJV4manNwWOjfiuPiOGpaAgxQWIZvQskGsW68U0jIpQnW1Fjm95D6BEMztLBQ==

ports:
  - name: main
    containerPort: 1411

gateway:
  host: id.wagner.gg

homepage:
  name: Pocket ID
  group: Cloud
  description: OIDC Provider
  icon: pocket-id.svg
  weight: 15
