image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.7.7@sha256:ad86dbfd24dd2103cd6e6605ced50e2baf488d20343ead704cd81cfa5a0c7ea4"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
