image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "2.2.0@sha256:af26d58910447ba3d3cae6619d5a66f5dfc11790fd7bbb4e77b33811303a4638"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
