image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "2.3.0@sha256:8e18ebc13b3da714cf593dae724d97f01cc16f25c6e253b8be2ca926568a27f0"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
