image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.7.5@sha256:bd6d8b934310cecd10be8551be016912eac7cd8700884d152bcb5490e7b99476"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
