image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.11.1@sha256:5aecdcc4c81079712bbc3d1945f4495edae2ccae07eaae5f9f1a0879c0c3f4fd"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
