image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.8.1@sha256:b6508583be5bb47ebed93745c9ce394e04f40b947ed9759eca993035143828b3"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
