image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "2.1.0@sha256:f7544d2c59aec118b1346ff79e4837b3cb216c889073f2857e079389957308bc"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
