image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.15.3@sha256:883f7b25ec62907d393e1e912d72aa8ab04147683f941eef8e054b7de1f0141d"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
