image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.10.0@sha256:83922061c6507d6747ba6547893778ca7d2dba9db3b699ebc90d997df9ff9532"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
