image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.7.4@sha256:87b3bc2853aa6581fa77d1aff883145b042e02668bcd9ae05b229013f0306637"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
