image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "1.16.1@sha256:230cd4eeabc5eee2994bf8e65f6caf72d3eec0f5af96c80a74331e7bf6e5aeda"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
