image:
  repository: "ghcr.io/alam00000/bentopdf-simple"
  tag: "v1.7.3@sha256:8a4dfbdecfb72a3491780cd24fd36c18ed0188f1efa5a80845a610f7b55845ef"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: bentopdf.wagner.gg

homepage:
  name: BentoPDF
  group: Organization
  description: PDF Tools
  icon: bentopdf.svg
  weight: 40
