image:
  repository: "ghcr.io/flaresolverr/flaresolverr"
  tag: "v3.4.4@sha256:06c76759d062c185d8ac0b48f302258645b8d99db86109a3d6dce3209d93de51"

ports:
  - name: main
    containerPort: 8191

health:
  path: /health
