image:
  repository: "ghcr.io/flaresolverr/flaresolverr"
  tag: "v3.4.5@sha256:4f4e5f759aa3a9a64305e99188ea1db1ec2944a5e7d290d2b089af5f2f6f48e4"

ports:
  - name: main
    containerPort: 8191

health:
  path: /health
