image:
  repository: "ghcr.io/flaresolverr/flaresolverr"
  tag: "v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e"

ports:
  - name: main
    containerPort: 8191

health:
  path: /health
