image:
  repository: "kopia/kopia"
  tag: "0.22.0@sha256:f81d4f52543a936cf52a6757ed41849e8719db3d71569a040530624bcd772406"

ports:
  - name: main
    containerPort: 51515

homepage:
  name: Kopia
  group: Server
  description: File Backups
  icon: kopia.svg
  weight: 5

gateway:
  host: kopia.wagner.gg

oidc:
  clientId: 92e183c2-e3d2-4357-86ea-1d42e515aefd
  clientSecret: AgBLQCTZOqLH1BNK1bt4mSqw9NIo0ChgG8HwySrMZ8eaVhz+M9/ffGsBVBCDsFnhomvIBJWzkLz/eyxu2l7XCtJkX3xzTKRab0ZCLiq6SbS/dCcqPRmlBg8TH96pXveKKAhg0AUK+jRGAI6z3dRW+qfsjTQ/RMwisvRGAR/as/0N9R0tvK3c/2RSMrn+vzSo40k3jBczv7P8qj8BRIOySA5c9z3clSHi9TQZSAGTmWETQwIacgquYnuR2cm4Oq7w8mZ1J5/oHuEid/rLaBgSOYEI0iw6u/hsngQkoEOr7XJGevjcGTpmslkQ1LRjW9cJCGxnQogx1G5kzn9VP714fBD8I791I7aBYb/tTtH2HdInpXic4jO290bZrDS69GuvEU/gOKYlpQe0BKbsnCaD0oOLWOYXEKwt9RGGiZP8S9kzGe+jvDqqHHZ92djV+YOJCu/CPYPuYfvVGpgcJ82ScRfFIQ1RHl2DwmxNDbGiufbL3ck8Wagv7+WySNDm7R4yyhJO+nj0+nv0vTLrKnZnb1ZrgnCBvEDuqDf0D/tPEooLdclAX2WAOCSjhCjI9IlOLMlXZlsA4v9Ecueu+/b4J1jyfrn2sz943I7l8bBOHDEbdZ0HsN3utHvdmtQnrlUxhMAi/IYx4meQx2Kx3Aq7fnB9J3yUXfXZGQIRPSZ/id5s/6nmUalbpUuiad6e+G0JhqTcnuQe+dTOZPHCAWMkKnmIcR4O0Q62+bEsrN1SRRiGJg==

args:
  - server
  - start
  - --disable-csrf-token-checks
  - --address=0.0.0.0:51515
  - --insecure
  - --without-password

envs:
  # disable warning about empty config
  - RCLONE_CONFIG: ""
  - RCLONE_CONFIG_PCLOUD_TYPE: pcloud
  - RCLONE_CONFIG_PCLOUD_HOSTNAME: eapi.pcloud.com

secretEnvs:
  - KOPIA_PASSWORD: AgASptr0Z/KexbHLdSN7BT06cJWBHXhRh6UXT6LUpm/7TRt/RGcqY6hcpy9hwSF829IqFZ8d/7H/7Als6hHtyL2FfWWvxeiBGpEcmz+i7q7tszb1I8nM7c5PdhQDLZSiDroaixlXK1GyLvccH1SmjH7oezwwF+9IF/J1iwIY8QlCGsTgbGQjJBWkuyJ8KpIQU2IHy6uRw/0zWrVKVAz1CSzHm0mGGE09CwXY2Ml5fhVil+Xf6LldiBgbfH2dvrpm7QdMOCd5YhfvhE/4YxOvF2fIRGaeIKA6tPGII1p0dHsmx6RP4/nGnmqXpOnFtWQZaWkMku9YQhlq0Q5ieg++sSgrs/HYcbco4Av9NhFtCRH49CpxK1Um1J63OtmmFWLu9PbCUhPlsKpPE14rm6YVVuonqZDjJLeWVrSDOciWnxEk0ghgRFimkRRBuXACT2d7hqMnTKh9t3qxuxMOxypv2thqlNi4BfBpBzbvNWn2WaAOXIIpCRaGZJElQRlDtMmMqM8xOOBpohMsZCsgHwYpPxalzCWwW90hGvE6Ga/Sj4NS8UTDb8y0ZBG3sgmln4MqRCawGdJJWHY9GJA3c+aA0gfF4lC3WBtyvWGS+O7gETXKBJCtf3Kl7y59KdTJLJK4CWizLG1fXPVUWi2BgohgwosepYge7goPInrCYIVUpp/dep+eUFFcS8dOPIilgvp26LjDer3SB9N+DaTIPplnacbntcVUrKJHt2RPirjm4XOwKbEod1CotxABerpXtAj7IrbS31H93mIOE5gD1/9JacUB7lif6XbAa9ozQWO9NUgNfZSOUNJ7UvCDXiqpchy2p9UY5jmsDeU/qxyDizfY8DkYLeKcOPkbKWVv1RUL1jo9YA==
  - RCLONE_CONFIG_PCLOUD_TOKEN: AgCbT/QLJO75umEb919cM0dE87uJd11NTByF+O2bNOHJ67b18mwBJsa/jcPoVC9hGxCEX8v1ODNXAWx+KVsxVNI/F2hST//munhsT4ZpN+r5eHJQRWdxOf5JtgaqFhMn/CSPE4sIVu8vZuqMv5s7bLZ1+zLxlmHEVmckJRnQd/p0AiHkTi5Rdsm90PUsqjiY+KWgswBM4TMP1mxSbcWSGsrC01Fbv7YHbQ073dva9FA6VP64LcHmKVYd55wTM0WHh6Qj9lNmNcN9bH+kd9VscYRJmipTMhaKUxPaABAF+QPUxO901oTGwSbXUL1cLk2t8OjMdHEq1wDMwlfKYBIKv+ezkst0cs74wc2mMXobWB2389UScqLeFNo04sNTDjAU4Ntq2kJxXI6lVlOYkF+410IJ0BbLqLum7tJYs+ZWejvE8h6rxovxRnHcdn0kk+anL5UvsaWhsT1IEv2aKbBjD6UCc/IxFklo2RCsyC1FYwbWu2u+xjlrpYYWcXMF+WofS3MmzfGYYFEulppq9j6S5JFd4yjeZYbyeIUpozPs4vupgaqLCRjPdm8422OMrjcmR1zOTdRymm6K4C2dqTUcc5NTJUZVxXdtB3R1EJKpQS1a08iwc5lrNNKwugZRgn/k8B8Xw+nZHzdXKSK1hmABoxVYfRhc+WBxbGLueDbXNnIwAcZ20aBdDaQmlX2f8ArIS6u9/Y6lknk21qC4vV89U0Aj6/3K/MCXoPhaZQXM3jC9yAz4/lg5LcKdF76Pv1zuJ8G2Iuj5ugm+7AUVzxR5iXNIFEo3sTokTvor6MYlDogcioD+SVm3gATauYfl6AOpCXSluY0TN5ievdzHVtmMAABtzE5AksDdMDH10A8q3Q==

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/kopia
    containerPath: /app/config
  - name: cache
    hostPath: /srv/nvme/scrap-data/kopia-cache
    containerPath: /app/cache
  - name: logs
    hostPath: /srv/nvme/scrap-data/kopia-logs
    containerPath: /app/logs
  - name: nvme
    hostPath: /srv/nvme
    containerPath: /srv/nvme
    type: Directory
    readOnly: true
  - name: restore
    hostPath: /restore
    containerPath: /srv/nvme/scrap-data/kopia-restore
