image:
  repository: "kopia/kopia"
  tag: "0.22.0@sha256:f81d4f52543a936cf52a6757ed41849e8719db3d71569a040530624bcd772406"

ports:
  - name: main
    containerPort: 8080

homepage:
  name: Kopia
  group: Server
  description: File Backups
  icon: kopia.svg
  weight: 5

gateway:
  host: kopia.wagner.gg

oidc:
  clientId: 92e183c2-e3d2-4357-86ea-1d42e515aefd
  clientSecret: AgBLQCTZOqLH1BNK1bt4mSqw9NIo0ChgG8HwySrMZ8eaVhz+M9/ffGsBVBCDsFnhomvIBJWzkLz/eyxu2l7XCtJkX3xzTKRab0ZCLiq6SbS/dCcqPRmlBg8TH96pXveKKAhg0AUK+jRGAI6z3dRW+qfsjTQ/RMwisvRGAR/as/0N9R0tvK3c/2RSMrn+vzSo40k3jBczv7P8qj8BRIOySA5c9z3clSHi9TQZSAGTmWETQwIacgquYnuR2cm4Oq7w8mZ1J5/oHuEid/rLaBgSOYEI0iw6u/hsngQkoEOr7XJGevjcGTpmslkQ1LRjW9cJCGxnQogx1G5kzn9VP714fBD8I791I7aBYb/tTtH2HdInpXic4jO290bZrDS69GuvEU/gOKYlpQe0BKbsnCaD0oOLWOYXEKwt9RGGiZP8S9kzGe+jvDqqHHZ92djV+YOJCu/CPYPuYfvVGpgcJ82ScRfFIQ1RHl2DwmxNDbGiufbL3ck8Wagv7+WySNDm7R4yyhJO+nj0+nv0vTLrKnZnb1ZrgnCBvEDuqDf0D/tPEooLdclAX2WAOCSjhCjI9IlOLMlXZlsA4v9Ecueu+/b4J1jyfrn2sz943I7l8bBOHDEbdZ0HsN3utHvdmtQnrlUxhMAi/IYx4meQx2Kx3Aq7fnB9J3yUXfXZGQIRPSZ/id5s/6nmUalbpUuiad6e+G0JhqTcnuQe+dTOZPHCAWMkKnmIcR4O0Q62+bEsrN1SRRiGJg==

args:
  - server
  - start
  - --disable-csrf-token-checks
  - --address=0.0.0.0:8080
  - --insecure
  - --without-password

envs:
  - RCLONE_CONFIG_PCLOUD_TYPE: pcloud
  - RCLONE_CONFIG_PCLOUD_HOSTNAME: eapi.pcloud.com
  # disable warning about empty config
  - RCLONE_CONFIG: ""
  - RCLONE_BWLIMIT: 4M:off

secretEnvs:
  - RCLONE_CONFIG_PCLOUD_TOKEN: AgCbT/QLJO75umEb919cM0dE87uJd11NTByF+O2bNOHJ67b18mwBJsa/jcPoVC9hGxCEX8v1ODNXAWx+KVsxVNI/F2hST//munhsT4ZpN+r5eHJQRWdxOf5JtgaqFhMn/CSPE4sIVu8vZuqMv5s7bLZ1+zLxlmHEVmckJRnQd/p0AiHkTi5Rdsm90PUsqjiY+KWgswBM4TMP1mxSbcWSGsrC01Fbv7YHbQ073dva9FA6VP64LcHmKVYd55wTM0WHh6Qj9lNmNcN9bH+kd9VscYRJmipTMhaKUxPaABAF+QPUxO901oTGwSbXUL1cLk2t8OjMdHEq1wDMwlfKYBIKv+ezkst0cs74wc2mMXobWB2389UScqLeFNo04sNTDjAU4Ntq2kJxXI6lVlOYkF+410IJ0BbLqLum7tJYs+ZWejvE8h6rxovxRnHcdn0kk+anL5UvsaWhsT1IEv2aKbBjD6UCc/IxFklo2RCsyC1FYwbWu2u+xjlrpYYWcXMF+WofS3MmzfGYYFEulppq9j6S5JFd4yjeZYbyeIUpozPs4vupgaqLCRjPdm8422OMrjcmR1zOTdRymm6K4C2dqTUcc5NTJUZVxXdtB3R1EJKpQS1a08iwc5lrNNKwugZRgn/k8B8Xw+nZHzdXKSK1hmABoxVYfRhc+WBxbGLueDbXNnIwAcZ20aBdDaQmlX2f8ArIS6u9/Y6lknk21qC4vV89U0Aj6/3K/MCXoPhaZQXM3jC9yAz4/lg5LcKdF76Pv1zuJ8G2Iuj5ugm+7AUVzxR5iXNIFEo3sTokTvor6MYlDogcioD+SVm3gATauYfl6AOpCXSluY0TN5ievdzHVtmMAABtzE5AksDdMDH10A8q3Q==

hostPaths:
  - name: nvme
    hostPath: /srv/nvme
    containerPath: /srv/nvme
    type: Directory
    readOnly: true
