apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/l2announcement.yaml
  - base/ippool.yaml

helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: 1.17.1
  includeCRDs: true
  releaseName: cilium
  valuesFile: values.yaml
