apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-wagner.gg
spec:
  secretName: wildcard-wagner.gg
  dnsNames:
    - wagner.gg
    - '*.wagner.gg'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
