image:
  repository: "ghcr.io/plexguide/huntarr"
  tag: "8.2.23@sha256:86a329c72ef50db177890aff87b8d513bd1abdcc61307e9c7771b6fafc2570b2"

ports:
  - name: main
    containerPort: 9705

gateway:
  host: huntarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/huntarr
    containerPath: /config

homepage:
  name: Huntarr
  group: Indexer
  description: Hunt for missing Media
  icon: sh-huntarr.png
  weight: 20
