image:
  repository: "ghcr.io/plexguide/huntarr"
  tag: "9.1.5@sha256:8f6f2ba9e7c0b7dbc52e6b1fdc7503327d7f3725b9c9bc3dbe5dd93644d99c55"

ports:
  - name: main
    containerPort: 9705

gateway:
  host: huntarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/huntarr
    containerPath: /config

homepage:
  name: Huntarr
  group: Indexer
  description: Hunt for missing Media
  icon: sh-huntarr.png
  weight: 20
