apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/certificate.yaml
  - base/public.yaml
  - base/private.yaml
  - base/http-to-https-redirect.yaml

helmCharts:
  - repo: oci://docker.io/envoyproxy
    name: gateway-helm
    version: 1.7.0
    includeCRDs: true
    releaseName: envoy-gateway-system
    valuesFile: values.yaml
    namespace: network
