image:
  repository: "ghcr.io/jellyfin/jellyfin"
  tag: "10.11.2@sha256:749972be6e7d440a47531ee36c9e38ea7a6271c875f42e8a52851c39862b0773"

ports:
  - name: main
    containerPort: 8096

gateway:
  host: jellyfin.wagner.gg

health:
  path: /

envs:
  - JELLYFIN_PublishedServerUrl: https://jellyfin.wagner.gg

resources:
  limits:
    gpu.intel.com/i915: "1"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/jellyfin
    containerPath: /config
  - name: cache
    hostPath: /srv/nvme/scrap-data/jellyfin-cache
    containerPath: /cache
  - name: multimedia
    hostPath: /srv/hdd/multimedia
    containerPath: /srv/multimedia
    readOnly: true

homepage:
  name: Jellyfin
  group: Media
  description: Media Center
  icon: jellyfin.svg
  weight: 10
