{{- if .Values.configMaps -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
data:
{{- range .Values.configMaps }}
  {{- if kindIs "map" .content }}
  {{ .subPath | quote }}: |
    {{- toYaml .content | nindent 4 }}
  {{- else }}
  {{ .subPath | quote }}: {{ toYaml .content | nindent 4 }} 
  {{- end }}
{{- end }}
{{- end }}
