image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-6.0.4.10291@sha256:97bbe01d5e2af350c77e901c3fb529a47624beaf40b96856fa8c2ae246e6914a"

ports:
  - name: main
    containerPort: 7878

gateway:
  host: radarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: movies
    hostPath: /srv/hdd/multimedia/Filme-Radarr
    containerPath: /movies
  - name: live-music
    hostPath: /srv/hdd/multimedia/Live-Konzerte
    containerPath: /live-music

homepage:
  name: Radarr
  group: Indexer
  description: Movie Manager
  icon: radarr.svg
  weight: 12
