apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
spec:
  addresses:
  - 192.168.0.240-192.168.0.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-pool
spec:
  ipAddressPools:
  - main-pool
