image:
  repository: "ghcr.io/immich-app/immich-machine-learning"
  tag: "v2.5.0@sha256:5fee7f3e052c3d32d4edecafad68317394daae26f57d895fbd487886083725a7"

ports:
  - name: main
    containerPort: 3003

health:
  path: /

hostPaths:
  - name: cache
    hostPath: /srv/nvme/scrap-data/immich-machine-learning
    containerPath: /cache

resources:
  limits:
    gpu.intel.com/i915: "1"

envs:
  - IMMICH_LOG_LEVEL: debug
