image:
  repository: "ghcr.io/immich-app/immich-machine-learning"
  tag: "v2.2.3@sha256:bf339cbb44af6c2ef25d9128e1da51b2bec0cfd524846a83e3017c21bd71ddb4"

ports:
  - name: main
    containerPort: 3003

health:
  path: /

hostPaths:
  - name: cache
    hostPath: /srv/nvme/scrap-data/immich-machine-learning
    containerPath: /cache

resources:
  limits:
    gpu.intel.com/i915: "1"

envs:
  - IMMICH_LOG_LEVEL: debug
