---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - Root
  customizeComponents:
    flags:
      handler:
        kubelet-pods-dir: /var/lib/k0s/kubelet/pods
        kubelet-root: /var/lib/k0s/kubelet
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
