image:
  repository: "ghcr.io/lossless1024/streamonitor"
  tag: "latest@sha256:4707a38ad04f32b1e85a5d9d32e5e30580cbc339f81197e4bd598c69fc30a50c"

ports:
  - name: main
    containerPort: 5000

gateway:
  host: streamonitor.wagner.gg

envs:
  - STRMNTR_HOST: 0.0.0.0
  - STRMNTR_PASSWORD: ""

hostPaths:
  - name: configs
    hostPath: /srv/nvme/container-data/streamonitor/config.json
    containerPath: /app/config.json
    type: FileOrCreate
  - name: keys
    hostPath: /srv/nvme/container-data/streamonitor/stripchat_mouflon_keys.json
    containerPath: /app/stripchat_mouflon_keys.json
    type: FileOrCreate
  - name: downloads
    hostPath: /srv/downloads/torrent/streamonitor
    containerPath: /app/downloads
