image:
  repository: "ghcr.io/hotio/lidarr"
  tag: "release-3.1.0.4875@sha256:7b265421de254f9d8620d42c8d734b250b6db932b9e1349d3598bb5261f60d92"

ports:
  - name: main
    containerPort: 8686

gateway:
  host: lidarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/lidarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /music

homepage:
  name: Lidarr
  group: Indexer
  description: Music Manager
  icon: lidarr.svg
  weight: 11
