image:
  repository: "ghcr.io/atuinsh/atuin"
  tag: "18.3.0@sha256:678def8e9d59652a502759ca431f9c5b54ebdd5e9361507c7fcf24705c9862e0"

hostPaths:
- name: config
  hostPath: /srv/nvme/container-data/atuin/config
  containerPath: /config

ports: 
- name: main
  containerPort: 8888

ingress:
  host: atuin.wagner.gg

args:
- server
- start

envs:
- ATUIN_HOST: "0.0.0.0"
- ATUIN_PORT: "8888"
- ATUIN_OPEN_REGISTRATION: "false"
- ATUIN_DB_URI: postgres://$(TEMPLATE_DB_USERNAME):$(TEMPLATE_DB_PASSWORD)@$(TEMPLATE_DB_HOST):$(TEMPLATE_DB_PORT)/$(TEMPLATE_DB_DATABASE)

database:
  enabled: true
  type: postgresql
  hostPath: /srv/nvme/container-data/atuin/database
  rootPassword: AgBppqhNVWAzzfmGrEv2Yoz1OhIzGlhxfkKGRcsAJJCd2C2qbwAheKjjj0YHCud8ABrVU0RdaNm7dG3f2NUJkAW2cMX4kX2yMbTCvCCGPg9tRF4GI1Fg26ZVjYQpij06p8wIJIUHM0iauUhejOtemV24X/CEJk830V6GJJ4IsEjeofOPHasjESJr8/BOIJT71tUliYpyuH9HACxBitHX6Um9C50qNrN8K/MUrZWN/eIZB8pmvIJN084PEscMsYZkdTgT4SFpi3CK8t8KYjK/ZBUCDNYUlEY8bPDQFdv7Xcm5EucP4JwZPtJ26nHhEzSpcLdT2qr/Hf0CZ+22zASThAVMFqT4na+8MWKJXewYg27N/UJu+SS4R5U3J/6aSDDYX7TcxNcvi+j/s2saK34VVuTT5Q5IALbCy/26Bx+gjxuxIPbaec/Mcu/1Ni3GGfptBApadmr4IdhNYx6pu58l99i5Vc3R6q3vq05hQJe1TdtegEfJw5Ir6vA/rCCoHi3RqPS+qzzedP4d+uJGfjzum1aAk0Lv23cutzYv0LEp3U+wAaPrG9vg3LgsC8np3SlX7g+JH8z5nkcrBc/nFhkvSO+/tpxdW4tKS3WA/MMJlSHtoPeZE14QZtHcxRp1MdirOgoiU7p6cmoNPs52zNTDvUmcm2D+evb7XERY1giHPZHNcnT/Mb1piiPL1vpv8QlFGJybk3kqGfR7juTuuGnQDLUBfeKuE4OM6U1bbBtCCISfSkRykXbim2IgQBciemUia9DgltfVgIs4FfTPjkG/Afwa
