schedule:
  backup: "0 1 * * *"
  # cleanup: "0 6 2 * *"

restic:
  mode: init
  path: /srv/nvme/container-data
  exclude:
    - "*.log"
  iexclude:
    - radarr/MediaCover
    - lidarr/MediaCover
    - sonarr/MediaCover
    - tautulli/cache
    - stash/generated
    - stash/blobs
    - immich-data/thumbs
    - immich-data/encoded-video
    - Plex\ Media\ Server/Cache/PhotoTranscoder
