image:
  repository: "ghcr.io/tofran/restic-rclone"
  tag: "0.18.0_latest"

schedule:
  backup: "0 1 * * *"
  # cleanup: "0 6 2 * *"

envs:
  - RESTIC_REPOSITORY: "rclone:pcloud:restic/demo"
  - RCLONE_CONFIG_PCLOUD_TYPE: pcloud
  - RCLONE_CONFIG_PCLOUD_HOSTNAME: eapi.pcloud.com
  # disable warning about empty config
  - RCLONE_CONFIG: ""
  - RCLONE_BWLIMIT: 4M:off

secretEnvs:
  - RCLONE_CONFIG_PCLOUD_TOKEN: AgCbT/QLJO75umEb919cM0dE87uJd11NTByF+O2bNOHJ67b18mwBJsa/jcPoVC9hGxCEX8v1ODNXAWx+KVsxVNI/F2hST//munhsT4ZpN+r5eHJQRWdxOf5JtgaqFhMn/CSPE4sIVu8vZuqMv5s7bLZ1+zLxlmHEVmckJRnQd/p0AiHkTi5Rdsm90PUsqjiY+KWgswBM4TMP1mxSbcWSGsrC01Fbv7YHbQ073dva9FA6VP64LcHmKVYd55wTM0WHh6Qj9lNmNcN9bH+kd9VscYRJmipTMhaKUxPaABAF+QPUxO901oTGwSbXUL1cLk2t8OjMdHEq1wDMwlfKYBIKv+ezkst0cs74wc2mMXobWB2389UScqLeFNo04sNTDjAU4Ntq2kJxXI6lVlOYkF+410IJ0BbLqLum7tJYs+ZWejvE8h6rxovxRnHcdn0kk+anL5UvsaWhsT1IEv2aKbBjD6UCc/IxFklo2RCsyC1FYwbWu2u+xjlrpYYWcXMF+WofS3MmzfGYYFEulppq9j6S5JFd4yjeZYbyeIUpozPs4vupgaqLCRjPdm8422OMrjcmR1zOTdRymm6K4C2dqTUcc5NTJUZVxXdtB3R1EJKpQS1a08iwc5lrNNKwugZRgn/k8B8Xw+nZHzdXKSK1hmABoxVYfRhc+WBxbGLueDbXNnIwAcZ20aBdDaQmlX2f8ArIS6u9/Y6lknk21qC4vV89U0Aj6/3K/MCXoPhaZQXM3jC9yAz4/lg5LcKdF76Pv1zuJ8G2Iuj5ugm+7AUVzxR5iXNIFEo3sTokTvor6MYlDogcioD+SVm3gATauYfl6AOpCXSluY0TN5ievdzHVtmMAABtzE5AksDdMDH10A8q3Q==
  - RESTIC_PASSWORD: AgAyRpZBRZnc7pVYSPNlamscyP0NBfOYa70EA1DnxIBUwG8wHJJZQfN/VGHz/fXYQIecZCS/byTvqNUvnRH5VKNhuOK/igwsNLTafpbUTVzEPIH8di93lmw/QhRcNUcn6ZINrVYPFjVTPfnTYB8MgRA8qyzzWTyza6oVb8+/31nP1I3KS9iQRsBjOfz9e2xab4JFb1nSrr0svHmHX+Vmwa6oUQQttepxlO+ziofnG5TeMYDijgv3+8BOWs4m8BxfQBW5MmLmQZZN4K97R3Rs0vDsvDLU2Lv8yZ42GPaaDDASVci0n8vOkfAuo1ct2VVxGTzuhZMlIYXC8Fq40GgCZOetsdEkv7nvir+YgTw7BNMZ5JUthqIUJYRG1d+XnPRWCQRr1XxSARcaowT2rETlrAgbfrVQW4q5RpH+QSP0g8MPekANcrI7HPgl1VpcVfmMzOdtJSBMZUftyWEXbHYiP323eDvlJdDfSmFKCA6gaMBqQzSOgojhoLug/C3aX6UpBHgi8FBKc8VG0b/Pt9iWB7M3BMQIkE25jdtDuh9DNrFNT6dojsPL1oXGDbPmpNdFiLjh2WtNIdpHPb5LXus2c0/GsLKSKWdv3shYEt3zob46HSzH07OQlN8sOrSTuWTN8hpKx7CG4VEUHUIHhcnrzRuYZoVCSLjAMlBDUiyfRxwvYrsXxk9DfGqDffZ5+sTAIz0PNSlmK6rn76/ALds2o4dwkiQ89g12mTv36nAd/8JUo3bkZCiyIk8qnLRo5rA35NGRxo8QW3A/R8mS6azkJwzVEtTwLUuQDmSAGURRQ/6B6XUCSJxouNN7CUycamHGM84Sgrdlrhp+7x7bQlg2VulJjNEvywrpEvYAMFt9YomtaA==

restic:
  path: /srv/nvme/container-data
  exclude:
    - "*.log"
  iexclude:
    - radarr/MediaCover
    - lidarr/MediaCover
    - sonarr/MediaCover
    - tautulli/cache
    - stash/generated
    - stash/blobs
    - immich-data/thumbs
    - immich-data/encoded-video
    - Plex\ Media\ Server/Cache/PhotoTranscoder
    # reduce for demo
    - jellyfin
    - plex
    - immich-db-backup
    - immich-data
