image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.3.0.5236@sha256:06fb7cf94572ccce241f9a91d6b2f50e3bb6d13cd4f11e3596b96e066807ed44"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
