image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.3.0.5236@sha256:f1f896f0da04a356a407c45880a2c383c905254dd9ccfa153a1a484aee13f89f"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
