image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.3.0.5236@sha256:133dc692d0a3bf716f636a4cf51f9928f1824cbcbf7a295a40d1435767d5e1f6"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
