image:
  repository: "ghcr.io/mealie-recipes/mealie"
  tag: "v3.10.1@sha256:bf48f06fcb2bd3f242d6f703cd7860f18913df3b1a3c8e8b8194196a8b53f6f6"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/mealie
    containerPath: /app/data/

ports:
  - name: main
    containerPort: 9000

gateway:
  host: mealie.wagner.gg

envs:
  - BASE_URL: https://mealie.wagner.gg
  - ALLOW_PASSWORD_LOGIN: false
  - OIDC_AUTH_ENABLED: true
  - OIDC_CONFIGURATION_URL: https://id.wagner.gg/.well-known/openid-configuration
  - OIDC_CLIENT_ID: feb51284-6130-411d-a68d-99eb4f11260a
  - OIDC_PROVIDER_NAME: Pocket ID
  - OIDC_ADMIN_GROUP: admin
  - OIDC_USER_GROUP: mealie
  - SMTP_HOST: smtp.migadu.com
  - SMTP_PORT: 587
  - SMTP_AUTH_STRATEGY: tls

secretEnvs:
  - OIDC_CLIENT_SECRET: AgA/12/kgQqzVs3FETukTosMr0qCSzBh2b6xUuQSg0DNkM1PFJwxuhw6897PrTsWJGn4egPGyKZzGrbv3/gNR+9bq2V96CUQSyhLghSnnJxR2kv3mjnTMRzYkd3QnCQ6bv7tiImmGf9v9fBBQkfNw4lsBqXlNCGLFD5JTwOKgtOtwJ3jhaJOT9AI/Nc+VLdghFRGkARjcvoMnWcPz7+aeEF59R4lXe/Fo7kVOqCNC9WH4mjHGXUL07IEmQnkxZXseASPPycLAut123Q9W45MMXQHrEdVC1p+A+U6l2D8Fmaf4QjKeMiUHL8CkW9vbafJHN/Oz8t1MdUet3Ud3ruHEE/D/P4DybeHL98qRoh5uSIPvecUuRFFkWY1/SV54FbDqHHhC8YatoD27tZApRSv/4IT4FODwkZMSQFRO3YT29TLsdp4Vx9KnRJ8PizxhSI7UndPwaAAFY6H3//ghXqfJYa38DKv2a/AbhFtqgBEug1G0E+qfbCvbu8IK6R8W0NwH3z5DCyUp2jZSmvJY2qGk/stk42jnepRdKlB7sj0hybFMX2mxEowCANmrvEN6M3Y/vtm8yrX6QWU9wZXyijcaD6Z5I5ouj8POQhP+15y/GH6GKWRUu5vf3TIVQ1vS9a3CACCMGWrT8L5CIDQ90EtkgbFG0mj+mcq0tdVYxD7+CGnV+aRZyoYDWX7FnAHpVY3HdpJzbLXiZOF763ijFcoGHCyVIUgpYk4lGKrt/0r9gkm9Q==
  - SMTP_FROM_EMAIL: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
  - SMTP_USER: AgAoKYtSwS9CKLbr7KgboHvcMhACYPRy5MgD2MkZFMxQeLOJEKIROmMhwtMD59ZI4/3INTTLOnpXJZBBuoLh6gJqajylcwgb+jV9dYphp7byFqhQALiAad5MtmRkHT6bkXolaeR27EGG/qVNOPDwFfvF42xibygm1Xzwqbuav/P9CHIhrpFeDUe1VMrLupSGIJfOOnw94GzJ9PE84wxTSJtEkwRNg4B+8gw2dLIebVKrs1aHGIqQnrLeBPexNscCdurxhqSZthwgiGZYDIidqHJK8Jx47LADENqmjG3PLKH4B8WTVbialWaSxfXBKRfgCNNSzpn2KA7GUdA0it6igqWvIWhK46C7cs2/a/9FEG0dDEYN3SLuQZXdHdAiXeJlmUTJ15Y5riJwrXRGjXUSyzZUCvz/S5jBuE9GE27ie0uuG8IbKRfmjbXBooJDkIB6rUDwVsbAVwFFGRQkY5ImmH38VyEpkpBM6vf2hT6RXWpopnFVmtjhTT8ATjQBz9E48nTKcWJ1Co+qMCi9t/hQJPcvScNVY34yVvvczxhbBrewbDpJzQRl/fNAq7Grx32PKZj/0iRIR6EkmDbubRZHO+ROH5u4HeT2Pm2Iw/PUpm7ZeFT+Ddbxl4Qn8od3MspwkFADgCYdDdM+XDndwApmxnVhOWr3l+WnPg5ms4zcqva2v9AJAkx9P7VeVrEZn3RDBHt/IVNxeAGX0LML+PGPr5HUcAc=
  - SMTP_PASSWORD: AgCzzndqBjY2iJ746hwzJXiJ5vMOU43ubyIOICoV1k4VUZq/sdblc5t5jcYPIWwa2VC1NzRp5Xvaqq0PjcTjr/RDAwyVZ+9lwtJBI2E8/M9Zd99MjihcY1zVjB0uKRwIvDiIKieZ6WQfPiE4lPbGX7cHQzJTu8wItYZ246IzbKvZXi2oGANdWK6AOWb1M8lC2DTo7UJ6N+AjQZblk0T/Imw3kpnRTi3Z1pZOl6BbBNBHBx1zzGX2Bgk7uic1CoUNR0Np+rEF8Ji7lmBFczosjSpbf64jSLm6E8Uy+89HhijQgFqCqaxU0DMlNe617pmHQVWqI6BfWGvEJ+mMk0L7p9cRNx8NNlKVUAnu8zkRdZjp5ccbnIhjMEtGznS4+Z3Qcw8mHYaD3aaY30Wy/4RpfofUttHGp7YObS8IIEMBVF9otZkmFFjM2cFrZ4IG2Zzuat+T+hIsRv+YnD2rOOw/Q3PvvtvRdrGi5UrhdMDrfjO+SQfVDd3Bu+JUGzAWBkWR67ZXvpwZDTUzcFgUYrqfsDAYj4FEycvTfbVKRy65GxLdJWZxD1FvticZphWaWy+z3wuhbLjWacu+GHV86fl8q1dy+3JNwlAa2F1nF3wIVq3Q+VwZHC7RB2u+juJt0YsGc+3myFyYojIwq43xojDP3NztuQQOr73EpUUUrejA4DBWfwYuG5XVlb9OvhR7es9aPbJV4manNwWOjfiuPiOGpaAgxQWIZvQskGsW68U0jIpQnW1Fjm95D6BEMztLBQ==


homepage:
  name: Mealie
  group: Organization
  description: Rezept Manager
  icon: mealie.svg
  weight: 35
