image:
  repository: "ghcr.io/seerr-team/seerr"
  tag: "v3.0.1"

ports:
  - name: main
    containerPort: 5055

gateway:
  host: seerr.wagner.gg
  public: true

health:
  path: /api/v1/status

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/seerr
    containerPath: /app/config

homepage:
  name: Seerr
  group: Media
  description: Media Requests from User
  icon: overseerr.svg
  weight: 1
