image:
  repository: "ghcr.io/seerr-team/seerr"
  tag: "v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9"

ports:
  - name: main
    containerPort: 5055

gateway:
  host: seerr.wagner.gg
  public: true

health:
  path: /api/v1/status

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/seerr
    containerPath: /app/config

homepage:
  name: Seerr
  group: Media
  description: Media Requests from User
  icon: seerr.svg
  weight: 1
