apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: reactive-resume-v5
    valuesFile: values.yaml
    namespace: tools
  - name: generic-service
    releaseName: reactive-resume-chrome-v5
    valuesFile: chrome.values.yaml
    namespace: tools
