apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../helm-charts

helmCharts:
- name: generic-service
  releaseName: samba
  valuesFile: values.yaml
  namespace: storage
