image:
  repository: "ghcr.io/esphome/esphome"
  tag: "2024.9.1@sha256:dbaba425a3933aa44e6304064ee43dd69b3f5093f22137e884cd56661c19a62f"

hostPaths:
- name: data
  hostPath: /srv/nvme/container-data/home-assistant/esphome
  containerPath: /config

ports: 
- name: main
  containerPort: 6052

health:
  path: /login

ingress:
  host: esphome.wagner.gg

homepage:
  name: ESPHome
  group: Smart Home
  description: ESP devices Management
  icon: esphome.svg
  weight: 60

envs:
- ESPHOME_DASHBOARD_USE_PING: "true"

secretEnvs:
- PASSWORD: AgBmC8cZpMO+uGPu1vXljyJzCAo6AReW3jLe2+fqGMlctMFgyVHWBiV5dgbZoFx2b0F3zvLEmp7BI6p1XnGOySCGS9hXkkyieCh59v39aaBYrbdT/PXMtna1CZ++DfQ4O4mmv3wIuv5ivmClm866SiDoUPw1QzAE9zI3KfoIoRcD57H1ZKB7XypK1QkSHBzS0fXUMeY/KV7M3ocI0KR42YafdGRWDNYTawnYj0ByPeKXKxKyQIAMQDM1YIdcBAVvkokbAPhphJvv1QLqDW87zXfcWjTScZX1aq4OQsRQj+aa9PVKzWj2GxrwwlLgo2l3OS/e1G4bngts7zlln9L27qe8gzFeASnEaS49QjB0hl6uAnkaKlSEcFMEvS3Xc4n+KehmURccG4c4YBmc9tQhZhJbt2OcbXg7NM0NaMYxQpOEkqShn5LCYidsKwC0oMZrnAvp+9PriqdFL8ivcDi4j/wu/oD/z3rR5BjXQvDHfN+z8hyVAgynjO2jjT8JoLloOPneTcVERX7MiGg+PJ+fdbuabq+aSJb0N8QI4dZySJcU3Hwt2/pcgpsawTb9xvwyl8/j8GCtH84ipmFQD6WostnzCGr8fHjkKZ4YidYKKjvuU8FGQO+Fl45+yrV0sWydf5+1NOUsWoZ5L2PMreayL37c/LecybPj3K2Rs7EZy3HmAUyPheybCUNT65GZ/3AwBnE3qIzEbzi6S3qpTGZ/oHGbHB8S3yAA3fO6l9wY3nIc
- USERNAME: AgBXPCDphquhTTCFOS64LTsk3MiDApnn0SFK8YXcZmgDwS4fcLRxJRpO28bvv5Jc2THhy0XM0N2fq15xmVeTE+VemSA3ti0rIyavMEum9DX0ZlzYIivRlZVIgo952DlcNsFS8LB+xILVcFcmqxIGs5rwYFyV0n1YTGTO1cfaezlyzmayGVgAOU4qT2lcveMFgmGlRCIsAPwrxC3JfWdPcYNbPhyoBMxHf68qlyiWS93Uczg+qoF8OO2KhQMd5Lsw/Mob+7o1hqXdKUsUgaR5umPVZrj8xNtjR5aWtMrOm+xOYgp70Prz6bLat3KuxokvOVHyGQoewc4IipR+zpTrzAKtEM7pMpzz7AHiJGXVgP0n038+LdDfW3zWdwG+8ph3U3NYqdEJoUBlBnPmeHfj8lFDkJH1cDRxZRYvXlCuqkgiuVM6aSDDkZxWqEId03bdTOWNbOS2WeRUbzAqQNqvGK1hyZbLPHc6hj426CT+aKuydmeb592eeQ3KUdjZgP6v7kb4sMXoYTzgHKleveYfcxCo+wxE62q6+CLLmNRQhPcZ0JynQhnFOQmK9IIVdMWmXZau+Qs48wsboZE0p4uaLViIPaXJUVxUtyvpRGlsWadtQGeqhtwB1heSZrA54QeDi40xZulqboxYggD6bjXTnwo8AmViliKYt05Z5+MuMzhFzMj9EZm8FKcLiFXOb/wpQ9u0m2Vb4cA=
