image:
  repository: "lancachenet/monolithic"
  tag: "latest@sha256:96c8b132397c8afe6cb53616746da6a01536bf9164c97a0df0b21ef1765c3d10"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/lancache
    containerPath: /data/cache

ports:
  - name: main
    containerPort: 80
  - name: https
    containerPort: 443

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  loadBalancerClass: metallb

envs:
  - CACHE_MAX_AGE: 365d
  - CACHE_INDEX_SIZE: 500m
  - MIN_FREE_DISK: 100g
  - CACHE_DISK_SIZE: 1000g

health:
  type: TCP
