image:
  repository: "lancachenet/monolithic"
  tag: "latest@sha256:9b38136a8d4a3e58c74d5602493ce7e4819f457d3f467ed222ae65e1a47da0d3"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/lancache
    containerPath: /data/cache

ports:
  - name: main
    containerPort: 80
  - name: https
    containerPort: 443

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  loadBalancerClass: metallb

envs:
  - CACHE_MAX_AGE: 365d
  - CACHE_INDEX_SIZE: 500m
  - MIN_FREE_DISK: 100g
  - CACHE_DISK_SIZE: 1000g

health:
  type: TCP
