image:
  repository: "ghcr.io/browserless/chromium"
  tag: "v2.39.0@sha256:e205e37ea598e48ea01fdb5132fb3d5d4f87a9aecabeffe8da01c59dbc804461"

ports:
  - name: main
    containerPort: 3000

envs:
  - TIMEOUT: 10000
  - CONCURRENT: 10
  - EXIT_ON_HEALTH_FAILURE: true
  - PRE_REQUEST_HEALTH_CHECK: true

secretEnvs:
  - TOKEN: AgA9sgYuou1IoUquAFewFeylbv6OAt2hYlcZAci8f+XNpNiSRht67L2ncPO0eTznNVkwO9fFhCxn07VlJOhKGp+oXI3Kh0p5+cPByeVZn+as8wUh8GMC3WQZ8I+HehSRmZ/yoA2fGvxX2M5TiBmvSFlz6hzg1L5JJ7QOS26PKye6soNXWF17hAxljov6LW9s2vWHMIU6rce6miapGTuprh0t/w80iFkZ+NZgJPwpGtEl3JWgX0ToZB3dCdqz6Fv5YwROuXHB19aYWAQnoFUsN6pnXa+Tz94ch2drjNNQFJwiT/Rr7vlKMBpoAFn603oUpTohLFvHUppPA6wix7rA1PSZGx6DreERqrb6+pSLqkIVfd7f964+S7u8gtQ6ZbALoOOIy6l5eoiX3m+Ju6RgH34FR0P7C64o4Lm9nfuLP6Lc0t/ykuTw6/SC215yiWlIOEF1xPOFE5NM+bpRHTAWsWVD7AJq2IR8CJcRVbMXwLkOK56wEc6d9UHWjkwyY6dPSqb1qAyMCtp43si7eDztvjrM3xqa2LkUUWqobuxctKoGUUyb5xzuqek2RqHGqZDvLZz8bdUP6rOrUQVEJp1MZP2sii0NCY5DZ+MT0dacnkE9nblnCLUcfvEoZCSMQVPFIN8osTA+6pIDr2bR2dJtyktMV6qEduLIAemZkfnc+GgFSetuFm7IftneNWMshi+vO1Kb36kPiSHqzo7gvo3QtwQyArqYLpTe1QY54tBuzi8yIHlvgYaY3IY0Rcm0P9ifQd+N5Q8Zemz5OsCITRxcWllv

health:
  enabled: false
