image:
  repository: "ghcr.io/lossless1024/streamonitor"
  tag: "latest@sha256:2cb984fd6ffdd0f0ed6d9bdececdf2ed942d9aeda1ed7956a24b3b9bffcbf15a"

ports:
  - name: main
    containerPort: 5000

gateway:
  host: streamonitor.wagner.gg

envs:
  - STRMNTR_HOST: 0.0.0.0
  - STRMNTR_PASSWORD: ""
  - STRMNTR_RESOLUTION: 99999
  - STRMNTR_DEBUG: true

securityContext:
  runAsUser: 5000
  runAsGroup: 5000

hostPaths:
  - name: configs
    hostPath: /srv/nvme/container-data/streamonitor/config.json
    containerPath: /app/config.json
    type: FileOrCreate
  - name: downloads
    hostPath: /srv/downloads/torrent/streamonitor
    containerPath: /app/downloads

configMaps:
  - name: dummyfile
    mountPath: /
    subPath: .dockerenv
    content: ""
