# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: yamlfmt
on:
  push:

jobs:
  yamlfmt:
    runs-on: ubuntu-24.04
    container: ghcr.io/google/yamlfmt:0.20.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Format Code
        run: yamlfmt .
