# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: yamlfmt
on:
  push:

jobs:
  yamlfmt:
    runs-on: ubuntu-24.04
    container: ghcr.io/google/yamlfmt:0.21.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Format Code
        run: yamlfmt .
