# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: yamlfmt
on:
  push:

jobs:
  yamlfmt:
    runs-on: ubuntu-24.04
    container: ghcr.io/google/yamlfmt:0.20.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Format Code
        run: yamlfmt .
